### ISSUE TITLE
Support 1.21.3 please!

### ISSUE THREAD

**Issue by alexweber** [SaolGhra/Armor-Hud#1]

**Comment by SaolGhra** [comment]
Hello, I have been busy the past couple of weeks, this has been stopping me from keeping my mods up to date, but with a few free days I have upcoming I will get to work on this, I will post again once I have done this. <3

**Comment by SaolGhra** [comment]
As an update to this, as far as I can tell the fabric api for drawing textures in versions above 1.21.1 seems to be a bit buggy, I will continue to look for fixes in my spare time and once there is one available I will go through with that action. But for the mean time this will be put on hold, I'm sorry for any trouble this causes.

**Comment by SaolGhra** [comment]
https://modrinth.com/mod/armor-hud/version/2.3-1.21.3

Now the fabric api has been updated, i have been able to proceed with updating to later minecraft versions
